In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [28]:
df=pd.read_csv('Dataset/train.csv')
df.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,1
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,5
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,5

In [29]:
df.shape

(36992, 25)

In [30]:
df.describe()

,age,days_since_last_login,avg_time_spent,avg_transaction_value,points_in_wallet,churn_risk_score
count,36992.000000,36992.000000,36992.000000,36992.000000,33549.000000,36992.000000
mean,37.118161,-41.915576,243.472334,29271.194003,686.882199,3.463397
std,15.867412,228.819900,398.289149,19444.806226,194.063624,1.409661
min,10.000000,-999.000000,-2814.109110,800.460000,-760.661236,-1.000000
25%,23.000000,8.000000,60.102500,14177.540000,616.150000,3.000000
50%,37.000000,12.000000,161.765000,27554.485000,697.620000,4.000000
75%,51.000000,16.000000,356.515000,40855.110000,763.950000,5.000000
max,64.000000,26.000000,3235.578521,99914.050000,2069.069761,5.000000

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   36992 non-null  object
 1   Name                          36992 non-null  object
 2   age                           36992 non-null  int64
 3   gender                        36992 non-null  object
 4   security_no                   36992 non-null  object
 5   region_category               31564 non-null  object
 6   membership_category           36992 non-null  object
 7   joining_date                  36992 non-null  object
 8   joined_through_referral       36992 non-null  object
 9   referral_id                   36992 non-null  object
 10  preferred_offer_types         36704 non-null  object
 11  medium_of_operation           36992 non-null  object
 12  internet_option               36992 non-null  object
 13  last_visit_time               36992 non-null  object
 14  days_since_last_login         36992 non-null  int64
 15  avg_time_spent                36992 non-null  float64
 16  avg_transaction_value         36992 non-null  float64
 17  avg_frequency_login_days      36992 non-null  object
 18  points_in_wallet              33549 non-null  float64
 19  used_special_discount         36992 non-null  object
 20  offer_application_preference  36992 non-null  object
 21  past_complaint                36992 non-null  object
 22  complaint_status              36992 non-null  object
 23  feedback                      36992 non-null  object
 24  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(3), object(19)
memory usage: 7.1+ MB

In [32]:
df.isnull().sum()

customer_id                        0
Name                               0
age                                0
gender                             0
security_no                        0
region_category                 5428
membership_category                0
joining_date                       0
joined_through_referral            0
referral_id                        0
preferred_offer_types            288
medium_of_operation                0
internet_option                    0
last_visit_time                    0
days_since_last_login              0
avg_time_spent                     0
avg_transaction_value              0
avg_frequency_login_days           0
points_in_wallet                3443
used_special_discount              0
offer_application_preference       0
past_complaint                     0
complaint_status                   0
feedback                           0
churn_risk_score                   0
dtype: int64

In [33]:
df.columns

Index(['customer_id', 'Name', 'age', 'gender', 'security_no',
       'region_category', 'membership_category', 'joining_date',
       'joined_through_referral', 'referral_id', 'preferred_offer_types',
       'medium_of_operation', 'internet_option', 'last_visit_time',
       'days_since_last_login', 'avg_time_spent', 'avg_transaction_value',
       'avg_frequency_login_days', 'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='object')

In [34]:
type(df['Name'])

pandas.core.series.Series

In [35]:
df['Name']

0         Pattie Morrisey
1             Traci Peery
2         Merideth Mcmeen
3        Eufemia Cardwell
4            Meghan Kosak
               ...
36987            Cuc Tarr
36988      Jenni Stronach
36989       Luciana Kinch
36990       Tawana Ardoin
36991    Verlene Beaulieu
Name: Name, Length: 36992, dtype: object

In [36]:
df[['Name','internet_option']]

                   Name internet_option
0       Pattie Morrisey           Wi-Fi
1           Traci Peery     Mobile_Data
2       Merideth Mcmeen           Wi-Fi
3      Eufemia Cardwell     Mobile_Data
4          Meghan Kosak     Mobile_Data
...                 ...             ...
36987          Cuc Tarr           Wi-Fi
36988    Jenni Stronach           Wi-Fi
36989     Luciana Kinch           Wi-Fi
36990     Tawana Ardoin     Mobile_Data
36991  Verlene Beaulieu     Mobile_Data

[36992 rows x 2 columns]

In [37]:
df.internet_option.value_counts()

internet_option
Wi-Fi          12413
Mobile_Data    12343
Fiber_Optic    12236
Name: count, dtype: int64

In [38]:
df['internet_option'].value_counts()

internet_option
Wi-Fi          12413
Mobile_Data    12343
Fiber_Optic    12236
Name: count, dtype: int64

# Handling missing Data

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   36992 non-null  object
 1   Name                          36992 non-null  object
 2   age                           36992 non-null  int64
 3   gender                        36992 non-null  object
 4   security_no                   36992 non-null  object
 5   region_category               31564 non-null  object
 6   membership_category           36992 non-null  object
 7   joining_date                  36992 non-null  object
 8   joined_through_referral       36992 non-null  object
 9   referral_id                   36992 non-null  object
 10  preferred_offer_types         36704 non-null  object
 11  medium_of_operation           36992 non-null  object
 12  internet_option               36992 non-null  object
 13  last_visit_time               36992 non-null  object
 14  days_since_last_login         36992 non-null  int64
 15  avg_time_spent                36992 non-null  float64
 16  avg_transaction_value         36992 non-null  float64
 17  avg_frequency_login_days      36992 non-null  object
 18  points_in_wallet              33549 non-null  float64
 19  used_special_discount         36992 non-null  object
 20  offer_application_preference  36992 non-null  object
 21  past_complaint                36992 non-null  object
 22  complaint_status              36992 non-null  object
 23  feedback                      36992 non-null  object
 24  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(3), object(19)
memory usage: 7.1+ MB